-- ====================================================================
-- Full Supabase Migration Dump (Schema & Data via REST API)
-- ====================================================================

-- Table Structure for: employee_requests
CREATE TABLE IF NOT EXISTS public."employee_requests" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "employee_name" TEXT,
  "reason" TEXT DEFAULT ,
  "request_date" TIMESTAMPTZ DEFAULT now(),
  "status" TEXT DEFAULT 'Pending'
);

-- Table Structure for: employees
CREATE TABLE IF NOT EXISTS public."employees" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "name" TEXT,
  "contact_number" TEXT DEFAULT ,
  "address" TEXT DEFAULT ,
  "gender" TEXT DEFAULT 'Male',
  "age" INTEGER DEFAULT 0,
  "blood_type" TEXT DEFAULT ,
  "allergies" TEXT DEFAULT ,
  "pre_existing_conditions" TEXT DEFAULT ,
  "emergency_contact" TEXT DEFAULT 
);

-- Data for: employees
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('8d149739-4445-4adc-b73d-b48770ba7485', 'ALQUIROS, IAN FERNANDO CAPULONG', '0', 'Baliwag Bulacan', 'Male', 45, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('b110dae1-0ecf-4d45-8689-aee3bdfc4f9f', 'CANOZA, CLARICE ANNE GATUZ', '.', '.', 'Female', 34, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('9962e70e-d1bd-4823-b35d-480dce71f1b6', 'ABORDE, JOHN PAUL GARCIA', '0', '0', 'Male', 40, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7376a020-de7c-457d-a785-99d5d8d5b16f', 'ACUÑA, GELEEN GONZALES', '0', '0', 'Female', 30, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7546842d-539a-4006-a685-927b48aa3e83', 'ADRIANO, ARIEL ANGELES', '0', '0', 'Male', 49, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('e21d8515-fe1d-4799-9dd0-e0107990a249', 'ADRIANO, CHRISTIAN MERCADO', '0', '0', 'Male', 30, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('04af388a-efb0-4368-9ee2-b9821f3e6cbf', 'ADRINEDA, JESCIL SAN MATEO', '0', '0', 'Female', 34, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('cd063b34-38ba-498e-b91b-98fa4b7c3c65', 'AGTARAP, SUSARAH SANTOS', '0', '0', 'Female', 48, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('4b47fc0e-087b-4b18-8e30-8fa100695313', 'AGUSTIN, MIKE JEFFREY MANANGHAYA', '0', '0', 'Female', 34, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('b39af702-19c0-4ec7-aeac-d10b595b02d8', 'ALCANTARA, MARIA ELINA GONZALES', '0', '0', 'Female', 53, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('01ecbe36-0777-45d5-913d-fe2c65e78fc5', 'ALCANTARA, RONALD TORIBIO', '0', '0', 'Male', 53, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('cb8b565a-9054-4114-b1bf-3d58885aa453', 'ALEJANDRO, ROMEL BULAONG', '0', '0', 'Male', 54, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('950add50-2d6b-4239-a770-a9019e3e1afb', 'ALEJANDRO, ROMEO SANTOS', '0', '0', 'Male', 54, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('70b3ad48-0a38-457e-97b5-341ddb090220', 'ALQUIROS, IAN FERNANDO CAPULONG', '0', '0', 'Male', 45, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('b434e440-77a9-45c5-9d20-578348ad88f7', 'ALVAREZ, JEMILINA TRINA NARTE', '0', '0', 'Female', 28, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7cd124b1-7275-4d12-88ff-97f19af29f36', 'ANACLETO, EDUARDO DE GUZMAN', '0', '0', 'Male', 61, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('00f6a503-1c13-43b5-809c-a4f4ceefbcfd', 'ANGELES, REYMOND PANGILINAN', '0', '0', 'Male', 33, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('698bca58-95ca-4ac8-be43-019816d6b963', 'ANGELES, RONMEL DELA CRUZ', '0', '0', 'Male', 24, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('bdbde488-ded0-4861-83da-f724ab0be92b', 'ANIAG, RICARDO CRUZ', '0', '0', 'Male', 62, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('65ee1ad1-df11-43e9-b880-638acee083b0', 'ATIENZA, LLYOD CHRISTOPHER GONZALES', '0', '0', 'Male', 46, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('16826e14-c431-47e4-9cdf-bbeeefd30e6c', 'BALINGIT, MICHELLE DIMLA', '0', '0', 'Female', 40, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('720a32bc-91ab-4fce-bfd3-e3b85b835dcf', 'BAUTISTA, BILLY DAN BANAL', '0', '0', 'Male', 38, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('8795dc49-feae-45a7-ab4d-ab1ded6f08b0', 'BAUTISTA, GREGGY BEJAR', '0', '0', 'Male', 39, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('0170ddc1-6fcd-41a2-9f4e-eea74be407e4', 'BAUTISTA, RONALD RODRIGEZ', '0', '0', 'Male', 55, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('a571f220-53a3-42ad-a0f2-6f348e86eb7a', 'BAYLOSIS, ARIEL CEASAR SORIANO', '0', '0', 'Male', 42, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('4e9b8607-fb12-4585-842c-716c12cfe04a', 'BULAON, ANALIZA VICTORIA', '0', '0', 'Female', 58, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('07a563d0-704c-4024-8d9d-a4832ac4be95', 'BUÑAG, JAMES SANTOS', '0', '0', 'Male', 57, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('aa9d8894-9e1f-447c-ba50-ac7a37cd69f0', 'CANOZA, CLARICE ANNE GATUZ', '0', '0', 'Female', 34, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('5692a857-373a-4dff-a623-f7067439e9bb', 'CANOZA, JULIUS CEASAR, BELTRAN', '0', '0', 'Male', 43, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('60b7d9de-8d06-42be-9f00-92cc46e783f5', 'CANOZA, ROLAND RYAN ABAN', '0', '0', 'Male', 29, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('732badb5-201f-41d3-840f-a29d6b1f3f40', 'CARILLO, JAYPEE SANGOYO', '0', '0', 'Male', 42, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3c08e8f4-47ee-4909-b5ea-f1651682cf9d', 'CARILLO, MARC LEMUEL SALVADOR', '0', '0', 'Male', 27, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('be3277a4-f4ce-45ed-9258-d860db9fd358', 'CARILLO, SILVESTER SANTOS', '0', '0', 'Male', 36, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('6a7bbf54-c3d6-4022-b835-9fbc5324249f', 'CARPIO, BIEN LLANOS', '0', '0', 'Male', 41, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('75498b21-6aeb-4f66-997f-7e6606eaa961', 'CASTRO, ERNESTO ESPIRITU', '0', '0', 'Male', 44, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('247583bd-d10d-446c-82e7-5995a0bbb01f', 'CENTENO, HERMINIO MANGON', '0', '0', 'Male', 54, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('59606c4e-63f7-47c6-84de-dcd87cd06541', 'CENTENO, MARVINE STA. JUANA', '0', '0', 'Male', 29, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('f3a452b6-be9b-4740-b43d-b478f0eacd8c', 'COLLANTES, GLENN ALLAN FAJARDO', '0', '0', 'Male', 46, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('e76658cf-969b-4102-b078-eac0f1d80cb9', 'CRUZ, ADRIAN KIM MANINGAS', '0', '0', 'Male', 36, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('8139019b-aec1-4788-91a1-eafd647a0d69', 'CRUZ, AIMEE FELICIANO', '0', '0', 'Female', 29, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('31f0e906-9a5f-40cf-bdcb-0c03b4ad19f7', 'CRUZ, ALLAN JOHN DOMINGO', '0', '0', 'Male', 44, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('5e4cf11b-7595-4434-a539-47aa79366bdc', 'CRUZ, CARLO ESPIRITO', '0', '0', 'Male', 37, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('944a4a7a-140d-46a8-bad6-9766482c0c28', 'CRUZ, MARI ANJELYN GUMARAN', '0', '0', 'Female', 29, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('ffe736ee-a370-4c8f-8539-6b08eb04e089', 'CRUZ, MARIO RODRIGEZ', '0', '0', 'Male', 56, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3977550f-04e6-4635-8ee7-7ebc03fa79b3', 'CRUZ, MAY ANNE ROBES', '0', '0', 'Male', 44, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('b436cef3-500d-40f9-9554-384f8d77c487', 'CRUZ, NICASIO ISIDRO', '0', '0', 'Male', 59, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('afa5a7b9-1ca5-419c-b512-60cef7a29475', 'CRUZ, NIÑO JASTYNNE VINCULADO', '0', '0', 'Male', 40, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('2f77db50-d640-4e88-a943-d1cbfd811fd5', 'CRUZ, RENATO CRUZ', '0', '0', 'Male', 62, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3e1ae13f-6e55-44ac-9476-839eeaec00d5', 'CRUZ, RODOLFO SANTOS', '0', '0', 'Male', 54, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7fa9d46a-f43e-4b09-8e03-8256debc9697', 'CUEVAS, RENALD TOLIONGCO', '0', '0', 'Male', 41, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('780a4342-d65c-48aa-9097-33584607b942', 'DALISAY, JEFFRY NIÑO FRANCISCO', '0', '0', 'Male', 42, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3a7c823a-a283-4f8c-bc8b-c19158a23a6a', 'DAYANDAYAN, ANACLETO TENORIO', '0', '0', 'Male', 53, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7e7e94b9-208f-4055-9a84-38466d12b989', 'DE DIOS, FERDINAND CABRAL', '0', '0', 'Male', 51, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('66d8969c-40d4-4c7f-87a7-47a31ecdf984', 'DE LEON, ALLAN GERALD CHICO', '0', '0', 'Male', 42, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('a656580c-9c02-4cc4-b3f9-a0b0507e82b3', 'DE LON, CHEENEE KEA DIAZ', '0', '0', 'Female', 26, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('51097232-14c5-4643-ade8-8c93a0565014', 'DE LEON, RODOLFO TAYAO', '0', '0', 'Male', 46, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('103ad9aa-4242-44cb-9cee-cde9882205ba', 'DEGNOS, JOMEL DE GUZMAN', '0', '0', 'Male', 32, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('9a343a39-33f5-4d22-9511-2caf78d11b16', 'DEL MAR, JOVIE CRUZ', '0', '0', 'Male', 32, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('f93d1b2c-ee8e-4f20-a394-5901b7bf16ff', 'DEL ROSARIO, RONEL SANTOS', '0', '0', 'Male', 37, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('2511bd43-1c79-4854-9fb3-a6c7eca3c518', 'DELA CRUZ, CESARIO CAO', '0', '0', 'Male', 44, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('81d4b84c-898a-44fd-b57f-d7dea581ef27', 'DELA CRUZ, LAARNI RIVERA', '0', '0', 'Female', 40, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3aa75945-73f4-488b-8f61-1413dce55ce0', 'DIEGO,EDUARDO CAHUMMA', '0', '0', 'Male', 42, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('86353e8f-de79-4493-b033-f39640ec79b0', 'ESTRELLA, KATHERINE JOY COLLANTES', '0', '0', 'Female', 29, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('85f889da-2e3d-4045-b08f-7808898ceb1a', 'ESTRELLA, LENNY BATAC', '0', '0', 'Female', 41, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7514f838-0bbd-4759-bd13-c9bb3f07fc8f', 'ESTRELLA, ROBERTO DE GUZMAN', '0', '0', 'Male', 62, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7dc0f850-e40c-46fe-bf3d-b633f3b6130f', 'EVANGELISTA, JOSE RAINIER MANUEL RAMOS', '0', '0', 'Male', 47, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('427b1014-a6c3-432c-94c3-7c1d74d61f5a', 'FABIAN, BERNARD PRINCIPIO', '0', '0', 'Male', 52, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('d24b290a-cbf6-4714-96b5-1fca17e946e6', 'FABIAN, CECILLA GONZALES', '0', '0', 'Female', 46, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('d07f26f6-3582-457d-afc4-892cc94d371c', 'FERNANDO, LEONIDES FONTILLAS', '0', '0', 'Male', 52, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('8139170d-c8fa-46eb-a738-26e72908ca75', 'FLORES, MA. CARLY LOUISE CASTRO', '0', '0', 'Female', 23, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('26eb03ec-93a3-4712-9ebf-211ede8a44c1', 'FRANCISCO, JOSEPH NOEL RAMOS', '0', '0', 'Male', 51, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('ede62b8b-00fc-446d-96e8-c1ca9ac0c12c', 'GABRIEL, ARNEL  FRANCISCO', '0', '0', 'Male', 54, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('011c3811-9c85-40c0-9067-60143d60d555', 'GARCIA, FRANCISCO FERNANDO', '0', '0', 'Male', 46, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3e89c522-1518-4f22-9ed9-ae56877aba99', 'GARCIA, MICHAEL FRANCISCO', '0', '0', 'Male', 54, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('1e0f5c7e-604a-4087-af74-8086b5f70b6c', 'GATMAITAN, ELIZAR NICODEMUS', '0', '0', 'Male', 36, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3818813a-9d46-430e-8a81-fa8159e1a08a', 'GENEBLAZO, PEPE INOFRE', '0', '0', 'Male', 49, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('dbf8622d-f2df-4393-93c3-c7a5e6b15e0b', 'GONZALES, ANDREA DELA CRUZ', '0', '0', 'Female', 23, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('c59c02fe-780c-4140-80c6-4c7fbfeb5c32', 'GONZALES, DENNIES JAVIER', '0', '0', 'Male', 53, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('07a3ad56-a76b-4d6c-92f4-c792a882ee72', 'GONZALES, FIDES MARAH CRUZ', '0', '0', 'Female', 48, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('ffc56a9e-8c2b-40f0-acb9-9d5ead8c5576', 'GUEVARRA, JOSELITO CASTRO', '0', '0', 'Male', 58, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('e5826baa-f328-418a-90dc-1ccde497ce11', 'GUITIERREZ, VINCENT JONH SAN MATEO', '0', '0', 'Male', 27, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('dd3557c5-2e41-45ee-b1c9-42445765b15d', 'HIPOLITO, JAYPEE RAMOS', '0', '0', 'Male', 41, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3183c091-f3f2-42c8-ab4f-6132b6571386', 'IGNA, ALDRIN DE GRACIA', '0', '0', 'Male', 33, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('c7b61bbc-e6de-4ae4-bf60-1b5b1e590fd5', 'IGNACIO, FARLYN ESTRELLA ', '0 ', '0', 'Female', 36, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7af7077e-ba7e-4b89-ac57-c16cedc7750b', 'JAVIER, RICARDO RIVERA', '0', '0', 'Male', 55, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('6817fad9-4a5e-4bfb-b2b5-c42abc49a333', 'JUGO, MARCELINO SAN MATEO', '0', '0', 'Male', 43, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('4de3b3d0-cc90-4bb1-845b-83d046a09fe5', 'JULIAN, JEROME BERNARD SANTOS ', '0', '0', 'Male', 40, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('84e23f10-cdb7-44bd-a3dd-c43dca31560c', 'LABAO, RISSA ANGELES', '0', '0', 'Female', 43, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('cf3d30e9-163e-40c5-ab35-9853569bb021', 'LAUCHANG, JAN EMIL CRUZ', '0', '0', 'Male', 40, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3f030bab-e9eb-41dd-b89a-1909e5136cb1', 'LAUCHANG, RACHELLE ANN CRUZ', '0', '0', 'Female', 34, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('20a02c27-394f-435c-b048-fd1849c11cf7', 'LAXAMANA, ETHEL JOY TARUC', '0', '0', 'Female', 33, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('41190cd8-18e3-4803-ba58-1a21dbe20841', 'LOPEZ, CHRISTINE FAYE SARMIENTO', '0', '0', 'Female', 27, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('86b86230-5659-4ce0-a412-82292af27611', 'LOPEZ, OHLYVER ANTIENZA', '0', '0', 'Male', 46, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('133b13b5-003c-4472-8196-4951a46c1d51', 'LUMABAN, CRISTOM ESPIRITU', '0', '0', 'Male', 43, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('84c18243-178f-4594-8796-3287d49d63d0', 'LUMABAN, JEROME TUGONON', '0', '0', 'Male', 28, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('9739850a-df27-49ed-800c-efe292dcc27c', 'MACAGBA, DAVID PERALTA', '0', '0', 'Male', 41, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('43c4c2f1-5fe3-4094-83e6-2621a3a7268d', 'MAGAT, MA. DENNISE SANTIAGO', '0', '0', 'Female', 29, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('699e64a9-61b5-45cd-8c26-3737f997cd9f', 'MAGSAKAY, RENDEL REAGAN PONCE', '0', '0', 'Male', 25, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('77d7ca4e-c602-430d-933d-4668acc2dba9', 'MANALASTAS, JENINA RAMOS', '0', '0', 'Female', 31, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('a2873434-b34d-41a1-884b-8603b1a2ef2c', 'MANALASTAS, JOHN JEFFERSON MENDOZA', '0', '0', 'Male', 31, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('d392f4f1-d0f9-49a2-be82-1f63f84f5f5e', 'MANAPOL, BENIGNO LUBASAN', '0', '0', 'Male', 42, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('d7fece88-e725-4702-a7d8-77b1a3dab3b1', 'MANIEGO, CHARMIE DANTIS ', '0', '0', 'Female', 43, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('da90768f-27e7-4e52-92c2-39c81905bf18', 'MANIEGO, NERISA CRUZ', '0', '0', 'Male', 33, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('978d7db2-d3ef-4c8c-bad1-174ecac1f289', 'MANIO, CATHY LAPIRA', '0', '0', 'Female', 32, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('2b0678e3-bae8-4040-9e08-3ee1ba82e57e', 'MANIO, JOEL AVEÑON', '0', '0', 'Male', 39, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('8d8cac24-b1c6-4fdf-b466-ea801343447f', 'MARASIGAN, JERICO MANANDIC', '0', '0', 'Male', 43, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('a589c61a-ba1b-40e5-b0c7-68cad9740656', 'MARCELO, JOSIELYN JOY SAN MATEO', '0', '0', 'Female', 31, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('0230f92c-cdfe-4c9b-bbae-4d43804ff0d2', 'MARCELO, MARK GIL MERCADO', '0', '0', 'Male', 44, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('5e8a614c-4fb1-45a8-970d-8ffb91e5b01a', 'MARCELO, RELIVIE TARUC ', '0', '0', 'Female', 38, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('b4c260ca-4528-43fa-afcf-d5d511b5ef20', 'MARCELO, RICHARD JOHN VALDISNO', '0', '0', 'Male', 50, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7c85567e-1ae1-4b35-b41d-b3658e4d48a0', 'MENDOZA, MA. LUZ CARDOZE', '0', '0', 'Female', 27, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('f9b48c49-13ea-4982-8d06-ce93509af556', 'MESTIDO, JOEL GONZALES', '0', '0', 'Male', 48, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('bd21815a-6d65-4d93-b83a-06ed9f045a8c', 'MONTOYA, PEE JAY MINAS', '0', '0', 'Male', 30, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('54ec966a-60df-4242-ba40-8e00a1cb9869', 'MONZONES, MARVIN ESTRELLA', '0', '0', 'Male', 47, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('682f40d7-0324-4ced-b0c5-6aed6242e187', 'MUNSAYAC, TANYA PATRICIA', '0', '0', 'Female', 24, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('0a20f13c-7a11-4627-b6ed-797dd7839390', 'NATIVIDAD, MARCELO GARCIA', '0', '0', 'Male', 39, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7f8fde36-028d-44ea-8fc3-ef5646b582cd', 'NOLASCO, GLENDA SANTOS', '0', '0', 'Female', 51, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('229f75c9-a9cd-4bc0-8583-c1c12e6d8863', 'OCAMPO, JAKE JOHNSON TOMAS', '0', '0', 'Male', 32, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('69d083d4-ad9a-4aca-bc47-12b7bd9b5fc2', 'ODICTA, ALEXANDER CRUZ', '0', '0', 'Male', 41, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('b35b377f-d4c8-4379-b79f-cf8026dec6b5', 'ONGLAS, DANILO LLANOS', '0', '0', 'Male', 38, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('ee58423b-180d-445b-8f45-e4e34e92c53d', 'OCHON, MARY FRANCINE VALENCIA', '0', '0', 'Female', 24, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('661c9d8f-05cc-4d4f-9f99-8c4fe0487526', 'ONGLAS, MARY GRACE DE DIOS', '0', '0', 'Female', 33, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('11f13af2-9725-49ee-ab43-43a7042fc071', 'ORBE, MARK GLEN SANTOS', '0', '0', 'Male', 32, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('f67b52ee-d441-42f0-a46c-88e6952ebdb6', 'PACUBAT, ARIEL CASTILLO', '0', '0', 'Male', 45, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('2ac1cc27-b2dc-4b86-b1f2-210b936e1b15', 'PAGKANLUNGAN, JOSE ANGELO PEREZ', '0', '0', 'Male', 34, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('cd9e8aa2-cd4b-4b3a-86fc-3a73062eb17e', 'PASCUAL, GIANINA DELA ROSA', '0', '0', 'Female', 31, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('1210e8e3-bf6c-4fc8-85d1-5320b4f66f0c', 'PASCUAL, RODGER CALUMBA', '0', '0', 'Male', 29, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('98b0bd21-6474-4127-bdb5-9c8a2bc42b56', 'PINEDA, RODELIO DELA CRUZ', '0', '0', 'Male', 51, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('2ec19690-6374-4a00-a06f-7eebec576467', 'PRIOLO, GLENN GARCIA', '0', '0', 'Male', 42, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('2dd492eb-0478-4a51-b1c6-fa86dd064f4b', 'PRIOLO, GLENN GARCIA', '0', '0', 'Male', 42, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('90a025e3-73fb-42da-8cb8-dfe645b2529b', 'RAGIL, NORMAN OLIVER PAMINTUAN', '0', '0', 'Male', 37, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('af3784de-3847-4cf5-b8e6-9ab9aedd0d29', 'RAMOS, ELOISA ESTEBAN', '0', '0', 'Female', 43, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('184c423c-629c-463c-a32c-3fe4d7543029', 'RAMOS, MA. TERESA FLORES', '0', '0', 'Female', 52, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('5c45ef26-9c5c-49ce-9fcb-d2dda953fd52', 'RAÑOSA, JONNET PABULOS', '0', '0', 'Male', 44, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('e704fd70-3d3a-4f0b-bdde-fe88423057a3', 'REYES, CECILIA RAMOS', '0', '0', 'Female', 52, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3ca0acb3-18ff-42dc-8074-5425ea622cfe', 'RODRIGO, CLARISSA VILLACARLOS', '0', '0', 'Female', 40, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('fe9cbff5-ecfa-46e3-8968-0e7eb18faf9f', 'SALAO, FERDINAND DEL ROSARIO', '0', '0', 'Male', 56, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('aa63277e-896e-4a91-843f-4e4a1bf7797f', 'SANGOYO, DESIREE DELA CRUZ', '0', '0', 'Female', 37, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('6fabf228-2288-435b-857e-f6fc58a687b6', 'SANTIAGO, JENNIELYN PELAYO', '0', '0', 'Female', 38, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('83b9b198-7cbc-4fae-88fd-05b9d7bc688d', 'SANTOS, ARIEL JULIANO', '0', '0', 'Male', 57, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('770a8ee8-389b-4929-9333-1fa46d01e25a', 'SANTOS, EDD VERDILLO', '0', '0', 'Male', 41, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('4e761fcc-96b4-4d3b-905a-931eb8991561', 'SANTOS, JENNIFER TORRES', '0', '0', 'Female', 52, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('b7728451-2021-4e52-ad02-3c31eacdfb22', 'SANTOS, MARVIN SANTOS', '0', '0', 'Male', 45, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('fe980a6e-7556-49b0-9eea-9be650491f11', 'SANTOS, ROSELL SAMANIEGO', '-', '0', 'Female', 53, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('7334e258-eb05-495b-8193-b40190951c42', 'SIGNO, MA.VICTORIA ESTRELLA', '0', '0', 'Female', 55, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('f68ad15a-8098-47ad-8330-bc70a3fb43c7', 'SISON, IGNATIUS SAN JOSE', '0', '0', 'Male', 47, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('4775b79b-3223-4d19-a152-fa73c978c844', 'SOLIAN, JEFFREY ROBANCHO', '0', '0', 'Male', 41, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('030d8177-8255-4b26-9c78-1539585e46fc', 'STA. JUANA, PIELITO PASCUAL', '0', '0', 'Male', 47, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('b9796a09-1756-46bd-87e7-683ba31003e1', 'STA. ROSA, JAIME RAFAEL DOMINGO', '0', '0', 'Male', 26, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('aec5eefc-41bf-4363-866b-70bdb0290779', 'SULIT, ALFREDO GUEVARRA', '0', '0', 'Male', 42, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('0acbee2a-6a99-4230-8e92-fb8140948dd8', 'TAGLE, JOMMEL RAMOS', '0', '0', 'Male', 37, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('dce538f8-4c7d-4318-b484-c3f721f42fa2', 'TIBURCIO, ELVYN CRUZ', '0', '0', 'Male', 51, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('ecfd66f8-59cb-4eae-8900-cd872b36b85c', 'TIMOTEO, CRISOSTOMO CABINGAO', '0', '0', 'Male', 54, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('5e3a1a2d-442d-46c8-80f5-00bf04402dab', 'TIOMICO, CHRISTIAN CARLOS', '0', '0', 'Male', 39, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('5a6cda6c-e83a-4e39-b97e-623523ec044d', 'TOLEDO, ROWELL PISCASIO', '0', '0', 'Male', 43, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('64c5553a-dbb3-478a-aa50-b310ce06b4e9', 'TOLENTINO, MA.ALELI SAUCO', '0', '0', 'Female', 48, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('bba1e478-bc2e-48d8-ae11-057e43112788', 'TORRES, DANILO FABIAN', '0', '0', 'Male', 58, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('3da8864c-8e71-4194-bce9-1f220009441a', 'TORRES, GLENN MICHAEL REYES', '0', '0', 'Male', 37, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('a75b6320-2a35-4453-b808-1236b8060c04', 'TORRES, JAKE WILSON DELA CRUZ', '0', '0', 'Male', 38, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('d2560508-6c4e-402a-a903-c081140d51ee', 'TRINIDAD, RAYMOND SULIT', '0', '0', 'Male', 42, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('fa9e316f-25e4-4a44-9f10-9b23c4e8889d', 'VALDERAMA, BENJAMIN GATMAITAN', '0', '0', 'Male', 55, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('757864ff-6837-4666-983b-d1b69e2c1b23', 'VALINO, CHRISTIAN LORENZ REYES', '0', '0', 'Male', 26, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('0d4fd99b-11da-43d6-a31b-589d78a7bfbe', 'VENTURA, FLORENTINO CASTILLO', '0', '0', 'Male', 46, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('a44f13f6-6951-448f-9121-a6051a975de9', 'VICHO, TEODORO SANTIAGO', '0', '0', 'Male', 53, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('c318baaa-4741-4ff4-8809-1bf006d601f1', 'VICTORIA, MARIA CRISTINA RAMOS', '0', '0', 'Female', 50, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('70fcc54a-7763-4966-94ab-01b1fd261b30', 'VILLA, FEL ANTHONY LAURON', '0', '0', 'Male', 31, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('69f7c9ea-6459-4b77-8c0c-1ff42766ccbe', 'VILLLAFENTE, ELGILBERT SAMSON', '0', '0', 'Male', 31, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('0ebf61b2-a2e0-4c50-b9d1-c916198be203', 'VILLAFUERTE, FE GATUZ', '0', '0', 'Female', 50, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('9eec5e3a-2058-4abb-94fb-724597126ac6', 'VILLAFUERTE, SEVERO TALLER', '0', '0', 'Male', 46, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('35048539-8b1d-4ee1-9366-ed79ca16caee', 'VILLANUEVA, KIM VILLANUEVA', '0', '0', 'Male', 36, '', '', '', '');
INSERT INTO public."employees" ("id", "name", "contact_number", "address", "gender", "age", "blood_type", "allergies", "pre_existing_conditions", "emergency_contact") VALUES ('80bace56-f10b-4532-8d26-35ebdd86e7e2', 'ZONA, MARK BRYAN VELASQUEZ', '0', '0', 'Male', 35, '', '', '', '');

-- Table Structure for: medicine_batches
CREATE TABLE IF NOT EXISTS public."medicine_batches" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "scientific_name" TEXT,
  "brand" TEXT,
  "milligrams" INTEGER,
  "added_date" TIMESTAMPTZ DEFAULT now(),
  "expiry_date" TIMESTAMPTZ,
  "illness" TEXT DEFAULT ,
  "quantity" INTEGER DEFAULT 0
);

-- Data for: medicine_batches
INSERT INTO public."medicine_batches" ("id", "scientific_name", "brand", "milligrams", "added_date", "expiry_date", "illness", "quantity") VALUES ('d5c076fb-3280-4579-9562-481f4f7ddb13', 'Paracetamol', 'Biogesic', 500, '2026-03-12T13:43:26.208296+00:00', '2026-06-30T00:00:00+00:00', 'Fever', 47);

-- Table Structure for: medical_records
CREATE TABLE IF NOT EXISTS public."medical_records" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "employee_name" TEXT,
  "date" TIMESTAMPTZ DEFAULT now(),
  "temperature" NUMERIC DEFAULT 36.5,
  "systolic" INTEGER DEFAULT 120,
  "diastolic" INTEGER DEFAULT 80,
  "pulse_rate" TEXT DEFAULT ,
  "chief_complaint" TEXT DEFAULT ,
  "medicine_given" TEXT DEFAULT 'None',
  "management" TEXT,
  "remarks" TEXT
);

-- Data for: medical_records
INSERT INTO public."medical_records" ("id", "employee_name", "date", "temperature", "systolic", "diastolic", "pulse_rate", "chief_complaint", "medicine_given", "management", "remarks") VALUES ('0f4bf02f-70ba-4a07-968e-9f9c70976aea', 'ALQUIROS, IAN FERNANDO CAPULONG', '2026-03-18T00:11:02.227411+00:00', 36.5, 130, 90, '', 'Slightly Elevated BP - For BP monitoring', 'None', NULL, NULL);
INSERT INTO public."medical_records" ("id", "employee_name", "date", "temperature", "systolic", "diastolic", "pulse_rate", "chief_complaint", "medicine_given", "management", "remarks") VALUES ('ca8e3abd-b299-45c4-907f-ebf3ed8fbf00', 'REYES, CECILIA RAMOS', '2026-06-15T06:24:21.496301+00:00', 36.5, 140, 90, '', 'for BP monitoring only. BP rechecked - 130/90. Advised to have Low Salt Low Fat Diet and increase water intake.', 'None', NULL, NULL);

-- Table Structure for: request_items
CREATE TABLE IF NOT EXISTS public."request_items" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "request_id" UUID,
  "medicine_name" TEXT,
  "quantity" INTEGER DEFAULT 1
);

-- Table Structure for: disposed_medicines
CREATE TABLE IF NOT EXISTS public."disposed_medicines" (
  "id" UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  "scientific_name" TEXT,
  "brand" TEXT,
  "milligrams" INTEGER,
  "quantity" INTEGER,
  "added_date" TIMESTAMPTZ,
  "expiry_date" TIMESTAMPTZ,
  "disposed_date" TIMESTAMPTZ DEFAULT now()
);

